services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME:-pii_labeler_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5433}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    volumes:
      - ./backend:/code
      - ./frontend/templates:/code/templates
    ports:
      - "${BACKEND_PORT:-8008}:8008"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=${DEBUG:-True}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-pii_labeler_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - TIME_ZONE=${TIME_ZONE:-Asia/Seoul}
      - LANGUAGE_CODE=${LANGUAGE_CODE:-ko-kr}

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-8000}:80"
    depends_on:
      - backend

volumes:
  postgres_data: