services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: pii_labeler_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"  # 외부 포트 5432로 변경
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8080"
             python create_superuser.py
    volumes:
      - .:/code
    ports:
      - "8080:8080"  # 외부 포트 8080로 변경
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=pii_labeler_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres

volumes:
  postgres_data:
