# Generated by Django 4.2.7 on 2025-09-12 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(max_length=200, verbose_name='data_id')),
                ('number_of_subjects', models.TextField(verbose_name='number_of_subjects')),
                ('provenance', models.TextField(verbose_name='provenance')),
                ('text', models.TextField(verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '문서',
                'verbose_name_plural': '문서들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PIICategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True, verbose_name='PII 값')),
                ('background_color', models.CharField(max_length=7, verbose_name='배경색')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': 'PII 카테고리',
                'verbose_name_plural': 'PII 카테고리들',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='PIITag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span_text', models.CharField(max_length=500, verbose_name='태그된 텍스트')),
                ('start_offset', models.IntegerField(verbose_name='시작 오프셋')),
                ('end_offset', models.IntegerField(verbose_name='끝 오프셋')),
                ('span_id', models.CharField(blank=True, max_length=100, verbose_name='Span ID')),
                ('entity_id', models.CharField(blank=True, max_length=100, verbose_name='Entity ID')),
                ('annotator', models.CharField(blank=True, max_length=100, verbose_name='주석자')),
                ('identifier_type', models.CharField(blank=True, max_length=100, verbose_name='식별자 유형')),
                ('confidence', models.FloatField(default=0.0, verbose_name='신뢰도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pii_tags', to='main.document', verbose_name='문서')),
                ('pii_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.piicategory', verbose_name='PII 카테고리')),
            ],
            options={
                'verbose_name': 'PII 태그',
                'verbose_name_plural': 'PII 태그들',
                'ordering': ['start_offset'],
            },
        ),
    ]
