# Generated by Django 4.2.7 on 2025-09-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='data_id',
            field=models.CharField(max_length=200, verbose_name='data_id'),
        ),
    ]
