# Generated by Django 4.2.7 on 2025-09-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_document_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='data_id',
            field=models.CharField(max_length=200, verbose_name='data_id'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('created_by', 'data_id'), name='uniq_user_data_id'),
        ),
    ]
