# Generated by Django 4.2.7 on 2025-09-11 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "문서",
                "verbose_name_plural": "문서들",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PIITag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pii_type",
                    models.CharField(
                        choices=[
                            ("name", "이름"),
                            ("email", "이메일"),
                            ("phone", "전화번호"),
                            ("address", "주소"),
                            ("ssn", "주민등록번호"),
                            ("credit_card", "신용카드번호"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                        verbose_name="PII 유형",
                    ),
                ),
                ("start_position", models.IntegerField(verbose_name="시작 위치")),
                ("end_position", models.IntegerField(verbose_name="끝 위치")),
                (
                    "tagged_text",
                    models.CharField(max_length=500, verbose_name="태그된 텍스트"),
                ),
                ("confidence", models.FloatField(default=0.0, verbose_name="신뢰도")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pii_tags",
                        to="main.document",
                        verbose_name="문서",
                    ),
                ),
            ],
            options={
                "verbose_name": "PII 태그",
                "verbose_name_plural": "PII 태그들",
                "ordering": ["start_position"],
            },
        ),
    ]
