"""
Django settings for pii_labeler project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False)
)

# Read .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default="django-insecure-60a0$&be0j(_(1s(fu8)7g5&$yox7$u9txk@jayd)h)#&&t+_m")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['114.110.130.188', 'localhost', '127.0.0.1'])

# CSRF 설정 (프론트엔드/백엔드 분리 구조용)
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://localhost:8015',
    'http://127.0.0.1:8000',
    'http://127.0.0.1:8015',
    'http://114.110.130.188:8015',
    'http://114.110.130.188:8080',
]
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False

# 개발 환경에서 CSRF 비활성화 (프로덕션에서는 제거해야 함)
if DEBUG:
    # 개발 환경 기본값
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_HTTPONLY = False
    CSRF_USE_SESSIONS = False
else:
    # 프로덕션 기본값 (HTTPS 전제 권장)
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "main",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pii_labeler.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pii_labeler.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env('DB_NAME', default='pii_labeler_db'),
        "USER": env('DB_USER', default='postgres'),
        "PASSWORD": env('DB_PASSWORD', default='postgres'),
        "HOST": env('DB_HOST', default='localhost'),
        "PORT": env('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Django가 생성/참조하는 정적 경로는 반드시 슬래시로 시작해야 함
STATIC_URL = "/static/"
# collectstatic 출력 경로 (컨테이너 빌드 시 필요)
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# WhiteNoise 압축/해시 스토리지(프로덕션 권장, 개발에서도 무해)
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 로그인/로그아웃 리디렉션 설정
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'  # 로그인 후 메인 페이지로 이동
LOGOUT_REDIRECT_URL = '/'  # 로그아웃 후 메인 페이지로 이동
